### ISSUE TITLE
broken links to files in the repo

### ISSUE THREAD

**Issue by vsfarrar** [ucdavisdatalab/workshop_how-to-data-documentation#1]
Links to files in the repo (stored in the template folder) do not work.  The broken links are currently in the [ Principles to Practice > Templates](https://ucdavisdatalab.github.io/workshop_how-to-data-documentation/#principles-to-practice) section.

**Comment by vsfarrar** [comment]
(First time using issues so wasn't sure who to assign - thank you for your help!)

**Comment by avkoehl** [comment]
I moved all the files into the docs folder in this pull request #2

**Comment by avkoehl** [comment]
> (First time using issues so wasn't sure who to assign - thank you for your help!)

No problem,  happy to help :).

**Comment by vsfarrar** [comment]
Solved by @avkoehl (see issue #2)
